#!/usr/bin/env node
/**
 * @kintsugi/sdk codegen
 *
 * 生成流程：
 *  1. 优先从环境变量 KINTSUGI_API_BASE 拉 /api/openapi.platform.json（live spec）
 *  2. 拉到后写入 spec/openapi.platform.json 作为快照（checked-in）
 *  3. 拉不到就退回用 spec/openapi.platform.json 现有快照
 *  4. 用 openapi-typescript 把 spec 编译成 src/generated/api-types.ts
 *
 * 这样：
 *  - 本地开发态 server 改 controller → 跑 `pnpm --filter @kintsugi/sdk gen` → 类型自动跟
 *  - 没有 server 也能 build（CI / 离线场景）
 *  - 快照进 git，PR 上能看到 spec 漂移
 */

import { writeFile, mkdir, readFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import openapiTS, { astToString } from 'openapi-typescript';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const PKG_ROOT = path.resolve(__dirname, '..');
const SPEC_PATH = path.join(PKG_ROOT, 'spec', 'openapi.platform.json');
const TYPES_PATH = path.join(PKG_ROOT, 'src', 'generated', 'api-types.ts');

const apiBase = process.env.KINTSUGI_API_BASE ?? 'http://localhost:4000';
const SPEC_URL = `${apiBase.replace(/\/+$/, '')}/api/openapi.platform.json`;

async function fetchLive() {
  try {
    const res = await fetch(SPEC_URL, { signal: AbortSignal.timeout(3000) });
    if (!res.ok) {
      console.warn(`[sdk:gen] live fetch ${SPEC_URL} → ${res.status}, falling back to snapshot`);
      return null;
    }
    return await res.json();
  } catch (err) {
    console.warn(`[sdk:gen] live fetch ${SPEC_URL} failed: ${err.message}, falling back to snapshot`);
    return null;
  }
}

async function loadSnapshot() {
  if (!existsSync(SPEC_PATH)) {
    throw new Error(
      `no live server at ${SPEC_URL} and no snapshot at ${SPEC_PATH}. ` +
        `Start the server (pnpm dev:server) and re-run, or check in a snapshot.`,
    );
  }
  const raw = await readFile(SPEC_PATH, 'utf8');
  return JSON.parse(raw);
}

async function main() {
  let spec = await fetchLive();
  let source;
  if (spec) {
    await mkdir(path.dirname(SPEC_PATH), { recursive: true });
    await writeFile(SPEC_PATH, JSON.stringify(spec, null, 2) + '\n');
    source = `live ${SPEC_URL}`;
    console.log(`[sdk:gen] wrote snapshot ${path.relative(PKG_ROOT, SPEC_PATH)}`);
  } else {
    spec = await loadSnapshot();
    source = `snapshot ${path.relative(PKG_ROOT, SPEC_PATH)}`;
  }

  const ast = await openapiTS(spec);
  const header =
    `/**\n` +
    ` * AUTO-GENERATED by packages/sdk/scripts/gen.mjs. DO NOT EDIT.\n` +
    ` * Source: ${source}\n` +
    ` * To regenerate:  pnpm --filter @kintsugi/sdk gen\n` +
    ` */\n\n`;
  await mkdir(path.dirname(TYPES_PATH), { recursive: true });
  await writeFile(TYPES_PATH, header + astToString(ast));
  console.log(`[sdk:gen] wrote ${path.relative(PKG_ROOT, TYPES_PATH)}`);
}

await main();
